"""empty message

Revision ID: 841d3415b2be
Revises: 10c72f375477
Create Date: 2022-10-27 17:54:21.374067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841d3415b2be'
down_revision = '10c72f375477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('poke_id', sa.Integer(), nullable=False),
    sa.Column('pokemon', sa.String(length=50), nullable=False),
    sa.Column('ability', sa.String(length=50), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('baseXP', sa.Integer(), nullable=False),
    sa.Column('sprite', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('poke_id'),
    sa.UniqueConstraint('pokemon')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.poke_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('catch_pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catch_pokemon',
    sa.Column('poke_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pokemon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ability', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attack', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('defense', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('baseXP', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sprite', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('poke_id', name='catch_pokemon_pkey'),
    sa.UniqueConstraint('pokemon', name='catch_pokemon_pokemon_key')
    )
    op.drop_table('team')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
